name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Ruby 2.6.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6

    - name: Set up Code Climate test-reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
    
    - name: Install bundler
      run: |
        gem install bundler
    - name: Install Dependencies
      run: bundle install
    - name: Set up test database
      run: bundle exec rake db:setup      
    - name: run Cucumber tests and capture coverage
      run: |
        bundle exec cucumber
        ./cc-test-reporter format-coverage --output coverage/codeclimate.$SUITE.json --input-type simplecov
    
    - name: Publish code coverage
      run: |
        export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
        ./cc-test-reporter sum-coverage coverage/codeclimate.*.json
        ./cc-test-reporter upload-coverage --id ${{ secrets.CODE_CLIMATE_ID }}
        ./cc-test-reporter after-build --id ${{ secrets.CODE_CLIMATE_ID }}
